print("git init -> cria um repositório Git local")
print("git clone <url> -> copia um repositório remoto para o local")
print("git status -> mostra o estado dos arquivos (modificados, não rastreados)")
print("git add <arquivo> -> adiciona mudanças à área de stage")
print("git add . -> adiciona todas as mudanças à área de stage")
print("git commit -m 'mensagem' -> salva as mudanças staged no histórico local")
print("git branch -> lista branches locais")
print("git branch <nome> -> cria uma nova branch")
print("git checkout <branch> -> troca para a branch especificada")
print("git switch <branch> -> alternativa moderna para checkout")
print("git merge <branch> -> mescla outra branch na branch atual")
print("git fetch -> traz referências remotas sem aplicar as mudanças")
print("git pull -> faz fetch + merge (ou rebase) para atualizar o local")
print("git push -> envia commits locais para o repositório remoto")
print("git log -> mostra o histórico de commits")
print("git diff -> mostra diferenças não commitadas")
print("git reset --hard <commit> -> volta o repositório para um commit (perigoso)")
print("git revert <commit> -> cria um novo commit que desfaz um commit anterior")
print("git tag <nome> -> marca um ponto no histórico (releases)")
print("git stash -> guarda temporariamente mudanças não commitadas")
print("git remote add origin <url> -> adiciona um repositório remoto")
print("git remote -v -> lista repositórios remotos e URLs")